### ISSUE TITLE
Tildes and backticks in info strings.

### ISSUE THREAD

**Issue by neongreen** [commonmark/CommonMark#119]
The spec says:

> Code fences (opening and closing) cannot contain internal spaces
> 
> Info strings for backtick code blocks cannot contain backticks

So:
- Both `~~~ ~~` and ```` ``` are not allowed as an opening code fence.
- ```` aa ```` isn't allowed either.
- Is `~~~ aa ~~~` allowed? stmd.js doesn't accept it, but it's not clear from the spec.
- For clarity, it should probably be mentioned that `~~~ ``` and ```` ~~` are allowed.

**Comment by jgm** [comment]
Some thoughts on this:

The only good reason for disallowing backticks in the info string is to allow the use of 3+ backticks for inline code, e.g.

    ``` hello ```

Of course, the solution is only partial; backtick style fenced code blocks mean that you can't hard-wrap this kind of inline code span; the closing backticks must be on the same line as the opener.  This is an argument against using backticks for fenced code blocks, but it's probably too well established in Markdown to change that.

Anyway, this reason for disallowing backticks doesn't apply to tildes, so perhaps tildes should be allowed in the info string.  A nice advantage of allowing them would be that you could write stuff like this:

    ~~~~~~ haskell ~~~~~~~
    f a >>= g >=> h
    ~~~~~~~~~~~~~~~~~~~~

which looks rather nice!

**Comment by jgm** [comment]
See also #197.

**Comment by Crissov** [comment]
[0.28](http://spec.commonmark.org/0.28/#fenced-code-blocks) says:

> The [info string] may not contain any backtick
characters.  (The reason for this restriction is that otherwise
some inline code would be incorrectly interpreted as the
beginning of a fenced code block.) 

This disallows ``~~~ info ` string `` etc. which seems unintentional given example 114:

> [Info strings] for backtick code blocks cannot contain backticks:
> 
> ~~~
> ```````````````````````````````` example
> ``` aa ```
> foo
> .
> <p><code>aa</code>
> foo</p>
> ````````````````````````````````
> ~~~

**Comment by robinst** [comment]
Ping. At the moment, the following results in a code block in commonmark.js ([dingus link](https://spec.commonmark.org/dingus/?text=~~~%20info%20%60%20string%0Atest%0A~~~)):

```
~~~ info ` string
test
~~~
```

But according to the spec it's not allowed:

> The info string may not contain any backtick characters.
