### ISSUE TITLE
Delimiters in link and image title attributes

### ISSUE THREAD

**Issue by wooorm** [commonmark/CommonMark#308]
Hey all, I’m currently in the process creating a [markdown parser/stringifier](https://github.com/wooorm/mdast) (no, not another one, rather, one that focusses on Markdown itself, not HTML :wink:).

During the process of adding CommonMark support, I came across the fact that it is not possible to generate a title attribute, which contains it’s delimiter, which works in Markdown.pl, GitHub, and CommonMark.

For example:
- `[Hello](./world.html "and "matching delimiters"")` works in Markdown.pl and on GitHub, but not in CommonMark;
- `[Hello](./world.html "and \"escapes\"")` works in CommonMark, but not in Markdown.pl or on GitHub;
- `[Hello](./world.html "and &quot;named entities&quot;")` works in CommonMark and Markdown.pl, but not on GitHub.

(The same goes for images.)

I understand CommonMark’s stand: it supports escapes and entities, to me the most logical ways to nest delimiters.

However, as those are not (universally) supported on other major systems, and because CommonMark is not yet at `1.0.0`, I want to propose added support for nested (both matching and non-matching) delimiters, at least for double and single quotes.

Is there any interest in adding this support?

---
# Support table:

| Implementation | Characters | Nested | Mismatched | Escaped | Named Entities | Numbered Entities |
| --- | --- | --- | --- | --- | --- | --- |
| Markdown.pl | `"` | Yes | Yes | No | Yes | Yes |
| GitHub | `"` | Yes | Yes | No | No | No |
| CommonMark | `"` | No | No | Yes | Yes | Yes |
| Markdown.pl | `'` | Yes | Yes | No | Yes | Yes |
| GitHub | `'` | Yes | Yes | No | No | No |
| CommonMark | `'` | No | No | Yes | Yes | Yes |
| Markdown.pl | `()` | - | - | - | - | - |
| GitHub | `()` | - | - | - | - | - |
| CommonMark | `()` | No | Yes | Yes | Yes | Yes |
# Fixtures

```
# Links

## Double quotes

[Hello](./world.html "and text")

[Hello](./world.html "and "matching delimiters"")

[Hello](./world.html "and "mismatched delimiters")

[Hello](./world.html "and \"escapes\"")

[Hello](./world.html "and &quot;named entities&quot;")

[Hello](./world.html "and &#x22;numbered entities&#x22;")

## Single quotes

[Hello](./world.html 'and text')

[Hello](./world.html 'and 'matching delimiters'')

[Hello](./world.html 'and 'mismatched delimiters')

[Hello](./world.html 'and \'escapes\'')

[Hello](./world.html 'and &apos;named entities&apos;')

[Hello](./world.html 'and &#x27;numbered entities&#x27;')

## Parentheses

[Hello](./world.html (and text))

[Hello](./world.html (and (matching delimiters)))

[Hello](./world.html (and (mismatched delimiters))

[Hello](./world.html (and \(escapes\)))

[Hello](./world.html (and &lpar;named entities&rpar;))

[Hello](./world.html (and &#x28;numbered entities&#x29;))

# Images

## Double quotes

![Hello](./world.png "and text")

![Hello](./world.png "and "matching delimiters"")

![Hello](./world.png "and "mismatched delimiters")

![Hello](./world.png "and \"escapes\"")

![Hello](./world.png "and &quot;named entities&quot;")

![Hello](./world.png "and &#x22;numbered entities&#x22;")

## Single quotes

![Hello](./world.png 'and text')

![Hello](./world.png 'and 'matching delimiters'')

![Hello](./world.png 'and 'mismatched delimiters')

![Hello](./world.png 'and \'escapes\'')

![Hello](./world.png 'and &apos;named entities&apos;')

![Hello](./world.png 'and &#x27;numbered entities&#x27;')

## Parentheses

![Hello](./world.png (and text))

![Hello](./world.png (and (matching delimiters)))

![Hello](./world.png (and (mismatched delimiters))

![Hello](./world.png (and \(escapes\)))

![Hello](./world.png (and &lpar;named entities&rpar;))

![Hello](./world.png (and &#x28;numbered entities&#x29;))
```

**Comment by wooorm** [comment]
Note! I just posted this on [vmg/redcarpet#473](https://github.com/jgm/CommonMark/issues/308) too, in the hope that one of these two projects would update their title rendering to have at least one method in common.

**Comment by jgm** [comment]
I trust you saw this rationale in the spec:

> (Note: Markdown.pl did allow double quotes inside a double-quoted title, and its test suite included a test demonstrating this. But it is hard to see a good rationale for the extra complexity this brings, since there are already many ways—backslash escaping, entities, or using a different quote type for the enclosing title—to write titles containing double quotes. Markdown.pl’s handling of titles has a number of other strange features. For example, it allows single-quoted titles in inline links, but not reference links. And, in reference links but not inline links, it allows a title to begin with " and end with ). Markdown.pl 1.0.1 even allows titles with no closing quotation mark, though 1.0.2b8 does not. It seems preferable to adopt a simple, rational rule that works the same way in inline links and link reference definitions.)

Specifying a syntax that allows indefinitely nested paired quotes, and implementing this in an efficient way, doesn't seem to me to be worth it, given how rarely this is needed and given the availability of several alternative methods for including quotes in titles.

If you're just looking for a way to render a title containing a quotation mark into Markdown in a way that will work with multiple Markdown implementations, may I suggest using `&quot;`?

**Comment by jgm** [comment]
Oh, I see from your table that github's renderer doesn't like entities in titles.  Well, that seems a clear bug in redcarpet (one of many) and should be fixed there.

**Comment by wooorm** [comment]
I completely agree! TBH, I hope RedCarpet will fix entities, like what you suggest, and stated above in `Support table`, rather than adding support for nested literal entities—see the referenced issue on vmg/redcarpet. However, I’m not sure they will do so quickly.

**Comment by wooorm** [comment]
Just saw your comment, great you saw it. Again, I hope RedCarpet will fix this!
