### ISSUE TITLE
list or code block?

### ISSUE THREAD

**Issue by rlidwka** [commonmark/CommonMark#385]
Here is an interesting edge case:

``` md
  1. foo
    - bar
```

Question: what is the element on the second line?
- It could be a code block (because it's indented with 4 spaces)
- It could be a new unordered list
- It could be a paragraph continuation even (not list 'cause 4 spaces, not code block 'cause can't interrupt)

Looks very similar to this bug: https://github.com/jgm/commonmark.js/issues/60 , but now cmark and commonmark.js output agree, so I'm opening a ticket here.

Markdown-it parses it as a code block, referencing https://github.com/markdown-it/markdown-it/issues/179 . The reason is a bit vague: " - " marks first list as interrupted, but a code block takes over because it has priority.

So please add a relevant test to the spec.

**Comment by jgm** [comment]
Hm, this is a good case. I think it should be paragraph continuation, actually.
It's indented too far to start a new list. But the spec could be clearer on this.  Certainly there should be a case like this, but I need to think also about whether the rules might be clarified.

**Comment by timofonic** [comment]
I'm sorry, but I find using spaces very error prone when doing very fast typing...

Instead putting a space before the star symbol, I would prefer put two ones to make it nested. This syntax is clearer for me and less error prone..

I also don't like MarkDown doesn't disthingish between star, minus and plus symbols:
I think these would be explicit different symbols when rendering a list, they can be valid in different contexts:

- Minus symbol could be used as a main item instead.
     * But can be used as a list of negative points about certain item too. There's an inconsistency I would like to solve.
+ Plus symbol could be used as a list of positive points.

**Comment by jgm** [comment]
+++ Timofonic [Jan 08 16 11:42 ]:
>   I'm sorry, but I find using spaces very error prone when doing very
>   fast typing...
>
>   Instead putting a space before the star symbol, I would prefer put two
>   ones to make it nested. This syntax is clearer for me and less error
>   prone..

There are other light markup languages that do it this way
(asciidoc, wiki markup, etc.).  Maybe Markdown just isn't
for you.

**Comment by jgm** [comment]
We now have test cases like this, and the reference implementations have been fixed.
So, closing.
