### ISSUE TITLE
Add links between the HTML blocks and Raw HTML sections

### ISSUE THREAD

**Issue by ndw** [commonmark/CommonMark#401]
Per zzzzBov, making this a github issue.

In 4.6, I think it would be nice if the first occurrence of "Raw HTML" was a link to 6.8.

Similarly, in 6.8, I think it'd be nice if there was some linked reference to 4.6, "HTML blocks"

**Comment by ndw** [comment]
I suppose now that I've found the github repo, I should probably just make a PR. If no one beats me to it, I'll see about doing that ... but probably not within the next day or two.

**Comment by jgm** [comment]
As I explain on the talk page, such a link would be misleading.

**Comment by ndw** [comment]
Fair enough. The improvement you suggest in the talk page would also help, I think.
