### ISSUE TITLE
Feature Request: iA Writer style transclusion syntax

### ISSUE THREAD

**Issue by xles** [commonmark/CommonMark#437]
Information Architects, the developer behind the very popular markdown editor (unfortunately not commonmark, yet) "iA Writer" for OSX recently released a new version, and with that, they included a proposed new transclusion syntax:
```
/filename
```
…and that's basically it.  For a better and more thorough description I refer to their own syntax document:

https://github.com/iainc/Markdown-Content-Blocks

I for one think this is a rather elegant option for a transclusion syntax, and who knows, maybe we can get iA on board the CommonMark train?

**Comment by jgm** [comment]
I don't think CommonMark should specify a transclusion
syntax.

This kind of thing should be handled with preprocessing
before passing things off to the CommonMark parser, it seems
to me.

**Comment by robsonsobral** [comment]
I don't know what to think about transclusion, but I'm afraid of the path iA is taking. They should be here talking.

**Comment by captain-digitalsailors** [comment]
If I may chime in: I think this change does not really fit to the idea of markdown. Neither is markdown a templating format (so transclusion should not be part of the spec), nor is the concept of "local" or a location readily available to a processor. (May make sense for local writing, but when a markdown file is moved to another location for processing, the location may change drastically.)

**Comment by anderflash** [comment]
In LaTeX we can use `\includegraph[...]{example}`. In this case I don't use an extension if I edit a LateX paper in Markdown (e.g. `![](example)`), which breaks the transclusion syntax `/example`.
