### ISSUE TITLE
"as described above" should be accompanied by a link

### ISSUE THREAD

**Issue by mgeier** [commonmark/CommonMark#480]
Or it should be told in some other way where to look.

Otherwise, it isn't really helpful. Because there's a lot of stuff "above"!

There are three occurrences, two of them right next to each other.

Just before http://spec.commonmark.org/0.27/#link-reference-definitions:

>  The exception is inside `<pre>` tags, but as described above, raw HTML blocks starting with `<pre>` can contain blank lines.

In http://spec.commonmark.org/0.27/#inline-link:

> The link’s URI consists of the link destination, excluding enclosing `<...>` if present, with backslash-escapes in effect as described above. The link’s title consists of the link title, excluding its enclosing delimiters, with backslash-escapes in effect as described above.

**Comment by jgm** [comment]
Agreed, these should be made into links whenever possible.
