### ISSUE TITLE
Feature request: Abbreviations

### ISSUE THREAD

**Issue by arm32x** [commonmark/CommonMark#481]
I request that PHP Markdown Extra abbreviations be added to the Markdown parser. They are structured like this:

```markdown
Hello MD!

*[MD]: Markdown
```

And outputs:
```html
<p>Hello <abbr title="Markdown">MD</abbr>!</p>
```

**Comment by Crissov** [comment]
This could be build upon shortcut reference kind but would look slightly different, e.g.:

~~~ markdown
Hello [MD]!

[MD]: ? "Markdown"
.
<p>Hello <a href="?" title="Markdown">MD</a>!</p>
.
<p>Hello <abbr title="Markdown">MD</abbr>!</p>
~~~

The question mark `?` is a nonsense link destination that the (virtual) postprocessor implementing the extension can be triggered with. A hash sign `#` or maybe a semicolon `;` would also work.

The asterisk could stay, but would yield an empty list that the postprocessor could remove:

~~~ markdown
Hello [MD]!

* [MD]: ? "Markdown"
.
<p>Hello <a href="?" title="Markdown">MD</a></p>
<ul>
<li></li>
</ul>
.
<p>Hello <abbr title="Markdown">MD</abbr>!</p>
~~~

**Comment by Crissov** [comment]
JFTR, @arm32x, this was discussed in [890] (https://talk.commonmark.org/t/abbreviations-and-acronyms/890) and [965] (https://talk.commonmark.org/t/abbr-tags-tooltips-using-link-syntax/965) on the Discourse site and should probably be continued there.
