### ISSUE TITLE
Add option to Smartypants to support thick space between sentences.

### ISSUE THREAD

**Issue by terrycloth** [commonmark/CommonMark#491]
### context

Adding extra space between sentences is a significant, albeit nowadays a minority, practice in typography. In contexts where consecutive spaces are preserved, such as word processors, one commonly just types double spaces after the period, but of course, spaces get collapsed to a single space when rendering HTML. You could set a CSS `white-space` property, but this can be tricky to get right if the prose is block-indented inside the markup. CSS also cannot neatly account for when the end of a sentence falls at the end of a line in the source markup, and trailing whitespace is stripped.

The best way to implement thick spaces between sentences in a rendered Web page is to actually use one of the thicker white space characters.

I was looking at implementing this feature myself in my particular workflow. But since I'm not the only person who likes a little extra breathing room between sentences, I figured I'd give a feature request here a shot.

### feature request

Add support for thick spaces after sentences. I think it would make sense as a feature of SmartyPants, but it would probably need to be optional.

### sticking points

* What sort of thick space should we use? I would personally suggest the en space (U+2002), but I guess unless there were some consensus here, this might have to be configurable too.
* A "normal" space (U+0020) does *not* collapse with other spaces, so normal and thicker spaces should not mix.
* Quoted English sentences put the quotation marks *after* the period, question mark, or exclamation point, and not every language ends sentences with the same punctuation, so the feature would need to detect and support multiple types of sentence separator.

**Comment by jgm** [comment]
The most difficult problem is detecting sentence boundaries.  To do this reliably, you have to know what is an abbreviation (e.g. `Mr.`) and this is highly language-dependent, and even discipline-dependent.  So I think this is out of scope for now.
