### ISSUE TITLE
Clarify if escaped space is allowed in link destination

### ISSUE THREAD

**Issue by robinst** [commonmark/CommonMark#493]
The spec for link destinations (without angle brackets) says:

> a nonempty sequence of characters that does not include ASCII space or control characters, and includes parentheses only if (a) they are backslash-escaped or (b) they are part of a balanced pair of unescaped parentheses. (Implementations may impose limits on parentheses nesting to avoid performance issues, but at least three levels of nesting should be supported.)

It's not clear whether an escaped space is valid or not, as in:

```
[foo](\ )
```

Currently, [the dingus produces](http://spec.commonmark.org/dingus/?text=%5Bfoo%5D(%5C%20)):

```
<p><a href="%5C%20">foo</a></p>
```

Thoughts?

**Comment by mgeier** [comment]
Spaces cannot be backslash-escaped, only punctuation.

The space in your example is not part of the "link destination", because this would not be allowed ("... does not include ASCII space ...").

The space is still allowed, because it's part of the [inline link](http://spec.commonmark.org/0.28/#inline-link):

> An inline link consists of a link text followed immediately by a left parenthesis `(`, optional whitespace, an optional link destination, an optional link title separated from the link destination by whitespace, optional whitespace, and a right parenthesis `)`.

IMHO, this is a bug in commonmark.js, other CommonMark parsers get it right: http://johnmacfarlane.net/babelmark2/?text=%5Bfoo%5D(%5C+).

**Comment by robinst** [comment]
Good point about being allowed in an inline link, so this is a slightly different test:

```
[foo](a\ b)
```

**Comment by mgeier** [comment]
Interesting, now there are two implementations with a bug: commonmark.js and markdown-it: http://johnmacfarlane.net/babelmark2/?text=%5Bfoo%5D(a%5C+b).

I remember some discussions about allowing spaces in link destinations (which would un-break many links on Github, for example), but this here is another issue.

**Comment by jgm** [comment]
I think the spec as stated should not allow

    [foo](a\ b)

as a link, so this seems to me an implementation bug
(in both cmark and commonmark.js).

**Comment by robinst** [comment]
Makes sense, thanks John. Updated commonmark-java.
