### ISSUE TITLE
Add *rationale* to the spec?

### ISSUE THREAD

**Issue by greggman** [commonmark/CommonMark#494]
It would be nice to know what the reasons are for certain decisions. Many spec have *rationale* sections and paragraphs explaining why something is the way it is.

For example I'd like to know the reason blank lines end most HTML blocks since the majority of users would likely get tripped up by this. I'd expect a user to be able to put a blockquote using html for example

    some markdown

    <blockquote><pre>
    "Args!"

    - some pirate
    </pre><blockquote>

And not expect the blank line to matter. That it does is fine but it would be great to understand the rationale since it will clearly confuse users.

It seems like it would be useful for that rationale added to the spec. 

To be clear **I am not asking for that rationale here on github issues**. I'm suggesting for rationale in general to be added to the spec. Many specs have this as it helps people understand the spec and also helps inform discussion. That's much more useful than when that rationale is lost to some internet discussion that happened somewhere else no one but the people in the discussion know about.

**Comment by jgm** [comment]
There is quite a bit of rationale in the spec (see e.g. on
list items).  However, we didn't include it for HTML blocks,
and it would be good to do so.

To answer your question, the main rationale for having blank
lines end HTML blocks is to allow users to put CommonMark
content inside these blocks.

    <div class="foo">
    *foo*
    </div>

gives you a div with `*foo*`; while

    <div class="foo">

    *foo*

    </div>

gives you a div with `<p><em>foo</em></p>`.

A secondary motivation is that we wanted it to be easy to
parse raw HTML blocks without backtracking, and without
building a sophisticated HTML parser into every conforming
CommonMark parser.

+++ Greggman [Aug 26 17 03:23 ]:
