### ISSUE TITLE
Can't mention to users that has underscores around the name

### ISSUE THREAD

**Issue by gfx** [commonmark/CommonMark#496]
For a name `@__gfx__` (it's my twitter account):

Input:

```
@__gfx__
```

Output (GFM is a CommonMark):

@__gfx__

I think it's a bug.

**Comment by vyp** [comment]
This isn't in the spec. AFAIK GFM is a superset of CommonMark, so this is a GFM issue, not a CommonMark one.

**Comment by gfx** [comment]
No, it's CommonMark's issue because GitHub can't fix it until CommonMark leaves a `@__xxx__` style token as is.

**Comment by vyp** [comment]
It follows the spec as far as I can tell:

http://spec.commonmark.org/0.28/#example-370
http://spec.commonmark.org/0.28/#ascii-punctuation-character

**Comment by gfx** [comment]
Yep, so I think it's a spec issue that should be fixed.

**Comment by mity** [comment]
> No, it's a CommonMark's issue because GitHub can't fix it until CommonMark leaves a `@__xxx__` style token as is.

So CommonMark specification should ask implementations to guess what extensions are written on top of it and behave appropriately for whatever the extensions implement? Sorry, but it does not make much sense to me unless you know how to implement the Oracle of Delphi.

**Comment by vyp** [comment]
@mity actually @gfx was just using the github comment as an example of using commonmark. The issue is commonmark converting `@__gfx__` to `@<strong>gfc</strong>` (as the spec says), instead of keeping it the same.

**Comment by mity** [comment]
@vyp So CommonMark specification should treat just this one particular extension from all the infinite set of potentially useful extensions?

Github defines and implements the extension. Ask Github to take `@` with higher priority then the `_` in their extension implementation, so the CommonMark's meaning of `_` is suppressed.

**Comment by vyp** [comment]
So this isn't about the `@`-mention GFM extension. @gfx wants the spec to change because they want to be able to correctly display their twitter account when using commonmark.

**Comment by mity** [comment]
Sorry, overlooked that.

But still, the special meaning of `_` can be suppressed by escaping: `@\_\_foo\_\_` -> @\_\_foo\_\_

**Comment by jgm** [comment]
So, we have the idea that `__` does not cause emphasis when
it's used inside a word (intra-word).  The question is how
to define precisely what that means.  Intuitively, one might
think, the `__` in `@__foo__` is intra-word.  But it isn't
intra-word the way we're defining that in the spec.

> A double `__` can open strong emphasis iff it is part of a
> left-flanking delimiter run and either (a) not part of a
> right-flanking delimiter run or (b) part of a
> right-flanking delimiter run preceded by punctuation.

In this case, the `__` is a left-flanking and right-flanking
delimiter run, but since it is preceded by puncutation,
it is allowed to open strong emphasis.

We certainly want some punctuation to appear like a word
boundary:  consider, for example, a quotation mark or a comma
or parenthesis:

    "__bold__, __italic__, and __small caps__," she said,
    should all be supported (__underline__ too).

But there might be some room for making the definitions
fancier in a way that would make the following sorts of
cases count as "intra-word":

    @__blah__@

Suggestions welcome.

**Comment by gfx** [comment]
@jgm 

Not just for mentions, there are programming languages that use `@`, `$`, `:` as part of identifiers and/or variable names: Perl, Ruby, JavaScript, Java (`$` is part of identifiers), and more. So I think it's better if `@__foo__`, `$__foo__`, `:__foo_` are written as is.

**Comment by jgm** [comment]
+++ FUJI Goro [Aug 29 17 18:25 ]:
>   [1]@jgm
>
>   Not just for mentions, there are programming languages that use @, $, :
>   as part of identifiers and/or variable names: Perl, Ruby, JavaScript,
>   Java ($ is part of identifiers), and more. So I think it's better if
>   @__foo__, $__foo__, :__foo_ are written as is.

This, to me, is not a compelling reason, because normally
you'd want to put backticks around code, and that works
fine: `$__foo__`.

**Comment by gfx** [comment]
@jgm So only `@` should be specialized for mentions? It's okay for me, but I think the simpler rule is better.

**Comment by jgm** [comment]
What simpler rule?  Can you state it precisely?  Remember
that we want to allow some kinds of punctuation around
underscore emphasis (see above).

+++ FUJI Goro [Aug 30 17 05:32 ]:
>   [1]@jgm So only @ should be specialized for mentions? It's okay for me,
>   but I think the simpler rule is better.

**Comment by gfx** [comment]
@jgm 

I agree with [your first comment on the thread](https://github.com/commonmark/CommonMark/issues/496#issuecomment-325718332). Thanks.

**Comment by Crissov** [comment]
You want a rule that makes nothing bold in `foo @__bar__ baz` but it should work when, say, highlighting part of an email address as in `foo@__bar__.baz`? Should it be different for asterisks, e.g. `foo @*bar* baz` vs. `foo@*bar*.baz`?

In my opinion, `@\_\_bar\_\_` would be tolerable and implementations of a _mention_ extension should probably also support autolinks for them, employing angular brackets: `<@__bar__>`.
