### ISSUE TITLE
Info strings after # line suffixes in ATX headings

### ISSUE THREAD

**Issue by Crissov** [commonmark/CommonMark#500]
# Status quo
> An [ATX heading](http://spec.commonmark.org/0.28/#atx-headings) consists of a string of characters, parsed as inline content, between an opening sequence of 1–6 unescaped `#` characters and an optional closing sequence of **any number** of unescaped `#` characters. 

[Highlighting mine.]

## Valid heading suffixes from spec examples
~~~ markdown
## foo ##
  ###   bar    ###

# foo ##################################
##### foo ##

### foo ###     
~~~

## Invalid heading suffixes
~~~ markdown
### foo ### b

# foo#

### foo \###
## foo #\##
# foo \#
~~~

# Proposal
I wonder whether we can somewhat relax the rule for the closing sequence of `#` characters. I want to enable something like an _info string_ for future extensions: If the number of unescaped `#` characters in the opening sequence is matched exactly by the number of unescaped `#` characters in a possible closing sequence with a space on both sides, the characters after this closing sequence form an _info string_ and are not used verbatim for output.

Only [example 44](http://spec.commonmark.org/0.28/#example-44) would be affected by this change:

~~~ markdown
### foo ### b
.
<h3>foo</h3>
~~~

instead of 

~~~ markdown
### foo ### b
.
<h3>foo ### b</h3>
~~~

Also:

~~~ markdown
### foo ### ###
### foo ### ##
### foo ## ###
### foo ## ### ##
.
<h3>foo</h3>
<h3>foo</h3>
<h3>foo ##</h3>
<h3>foo ##</h3>
~~~

And:

~~~ markdown
# foo `#`
# foo ` # `
.
<h3>foo <code>#</code></h3>
<h3>foo `</h3>
~~~

... where I'm not completely sure about the last one.

## Common use cases

~~~ markdown
# foo # #bar .baz "quuz"
# foo # {id=bar class=baz title=quuz}
.
<h1 id="bar" class="baz" title="quuz">foo</h1>
<h1 id="bar" class="baz" title="quuz">foo</h1>
~~~

The string either inside quotation marks `""`  or parentheses `()` would be used in the HTML `title` attribute, but also in a table of contents, i.e. LaTeX (`book`) equivalence would be like this:

~~~ markdown
# foo # "bar"
# foo # (bar)
.
\chapter[bar]{foo}
\chapter[bar]{foo}
~~~

There could also be an extension that made headings not have an auto-generated number or not being included in the ToC, or both, e.g.:

~~~ markdown
# foo # -
.
\chapter*{foo}
~~~

## Impact

I do not have a corpus available to test this proposal with, but I expect there to be very little existing contents that would be affected by the change, because the hash or number sign `#` is very unlikely to occur within a heading (or prose in general) with spaces on both sides of it. A string of `#` characters is even less likely. Authors who are talking of the character itself will very likely mark it up with directly adjacent backticks or quotation marks.

## Consequences

People would probably also like to have _info strings_ for setext headings if they were available for ATX headings. Their `=` and `-` underlines do not allow any contents in the same line either.  A possible, but hackish, solution would be to only consider trailing characters for an _info string_ if the underline length matches the characters in the (last line of the) heading.  

I am not proposing this behavior right now.

~~~ markdown
foo
=== #bar .baz "quuz"
foo
--- #bar .baz "quuz"
.
<h1 id="bar" class="baz" title="quuz">foo</h1>
<h2 id="bar" class="baz" title="quuz">foo</h2>
~~~

~~~ markdown
foo
==  ==  #bar .baz "quuz"
foo
- #bar .baz "quuz"
.
<p>foo ==  ==  #bar .baz "quuz" foo</p>
<ul><li>#bar .baz "quuz"</li></ul>
~~~

**Comment by vyp** [comment]
Also try proposing at https://talk.commonmark.org/.

**Comment by Crissov** [comment]
Related topics have been discussed there, e.g.:

- [Consistent attribute syntax](https://talk.commonmark.org/t/consistent-attribute-syntax/272)
- [Feature request: automatically generated ids for headers](https://talk.commonmark.org/t/feature-request-automatically-generated-ids-for-headers/115)
- [Anchors in markdown](https://talk.commonmark.org/t/anchors-in-markdown/247/20)
- [Enumerated lists without explicit number, ATX headings with explicit number](https://talk.commonmark.org/t/enumerated-lists-without-explicit-number-atx-headings-with-explicit-number/1951)
- [MultiMarkdown Cross References](https://talk.commonmark.org/t/multimarkdown-cross-references/1915)

I'm not sure it's worth raising this topic over there. I'm *not* proposing the `#id .class "title" @key=value` syntax (nor any other) for the _info string_, just that there be an optional _info string_ in ATX headings.

**Comment by vyp** [comment]
Oh right then, good point. I wanted to point you to the discourse in the case that you didn't know about or see it.

**Comment by Crissov** [comment]
I have started to edit spec.txt to make this change, but since I got almost no feedback, I’m actually not sure whether I should proceed with that. I also don’t feel competent enough to make the respective changes to the reference implementations.

**Comment by Crissov** [comment]
## [commonmark.js](https://github.com/commonmark/commonmark.js/blob/master/lib/blocks.js#L421)

~~~~ javascript
var reATXHeadingMarker = /^#{1,6}(?:[ \t]+|$)/;
~~~~
~~~~ javascript
    // ATX heading
    function(parser) {
        var match;
        if (!parser.indented &&
            (match = parser.currentLine.slice(parser.nextNonspace).match(reATXHeadingMarker))) {
            parser.advanceNextNonspace();
            parser.advanceOffset(match[0].length, false);
            parser.closeUnmatchedBlocks();
            var container = parser.addChild('heading', parser.nextNonspace);
            container.level = match[0].trim().length; // number of #s
            // remove trailing ###s:
            container._string_content =
                parser.currentLine.slice(parser.offset).replace(/^[ \t]*#+[ \t]*$/, '').replace(/[ \t]+#+[ \t]*$/, '');
            parser.advanceOffset(parser.currentLine.length - parser.offset);
            return 2;
        } else {
            return 0;
        }
    },
~~~~

**Comment by jgm** [comment]
I think this kind of discussion belongs in talk.commonmark.org, so we can keep this tracker more focused.

**Comment by Crissov** [comment]
Discussion continues there: <https://talk.commonmark.org/t/info-strings-for-suffixed-headings/2902>
