### ISSUE TITLE
code block after list renders incorrect

### ISSUE THREAD

**Issue by amkgo** [commonmark/CommonMark#510]
For the following markdown
```
* list 1

    code 1
    code 2
```
The [commonmark.js reference implementation](http://spec.commonmark.org/dingus/) renderred as
```
<ul>
<li>
<p>list 1</p>
<p>code 1
code 2</p>
</li>
</ul>
```
which is notwhat I want. How can I render it as
```
<ul>
<li>list 1</li>
</ul>
<pre><code>code 1
code 2
</code></pre>
```

Thanks,
Andrew

**Comment by Crissov** [comment]
- Empty comment:
  `````` markdown
  * list 1
  
  <!---->
      code 1
      code 2
  ``````
- Fenced code block:
  `````` markdown
  * list 1
  
  ```
  code 1
  code 2
  ```
  ``````
  or
  `````` markdown
  * list 1
  
  ~~~
  code 1
  code 2
  ~~~
  ``````

[Dingus](http://spec.commonmark.org/dingus/?text=*%20list%201%0A%0A%3C!----%3E%0A%20%20%20%20code%201%0A%20%20%20%20code%202%0A%0A*%20list%202%0A%0A%60%60%60%0Acode%201%0Acode%202%0A%60%60%60%0A%0A*%20list%203%0A%0A~~~%0Acode%201%0Acode%202%0A~~~%0A)

**Comment by amkgo** [comment]
Thanks.

**Comment by jgm** [comment]
This is according to spec, it's not a bug.
For workarounds see above.
The "two blank lines breaks a list" was part of early versions of CommonMark but has been removed.

**Comment by Crissov** [comment]
That explains why I thought it would work.
