### ISSUE TITLE
How to handle ATX and Setext style occurring together for the same heading?

### ISSUE THREAD

**Issue by Crissov** [commonmark/CommonMark#518]
If both are present, should implementations conforming to Commonmark prefer prefixed (ATX) headings or underlined (Setext) headings? 

~~~~ markdown
# Heading # 
===========

## Heading ##
-------------
.
<h1>Heading</h1>
<p>===========</p>
<h2>Heading</h2>
<hr>
.
<h1># Heading #</h1>
<h2>## Heading ##</h2>
~~~~

According to [Babelmark](https://babelmark.github.io/?text=%23+Foo+%23%0A%3D%3D%3D%3D%3D%3D%3D%0A%0A%23%23+Bar+%23%23%0A---------%0A), the reference implementations and most of the other ones prefer the `#` prefix, while Markdown.pl and Pandoc prefer the `=`/`-` underline, but I'm not sure which part of the specification leads to this interpretation. 

Should implementations perhaps collapse both, like Earmark and Gambas do? 

~~~~ markdown
# Heading # 
===========

## Heading ##
-------------
.
<h1>Heading</h1>
<h2>Heading</h2>
~~~~

But what to do when [they mismatch](https://babelmark.github.io/?text=%23+Foo+%23%0A-------%0A%0A%23%23+Bar+%23%23%0A%3D%3D%3D%3D%3D%3D%3D%3D%3D%0A)?

~~~~ markdown
# Heading #
-----------

## Heading ##
=============

### Heading ###
---------------
.
<h1>Heading</h1>
<hr>
<h2>Heading</h2>
<p>===========</p>
<h3>Heading</h3>
<hr>
.
<h2># Heading #</h2>
<h1>## Heading ##</h1>
<h2>### Heading ###</h2>
~~~~

If the markup should indeed be collapsed, Commonmark could specify unified headings markup with optional markup components for the top two levels. This probably means that `#` would have to be ignored when a matching underline but no (matching) prefix is present (which would be nice for info strings #500).

~~~~ markdown
Heading #
=========

Heading ##
----------
.
<h1>Heading</h2>
<h2>Heading</h2>
~~~~

Would two win against one?

~~~~ markdown
## Heading #
============

# Heading ##
------------
.
<h1>## Heading</h1>
<h2># Heading</h2>
~~~~

**Comment by jgm** [comment]
This issue is settled in the first paragraph under section 4.3 of the spec.

**Comment by Crissov** [comment]
🤔 Indeed. It seems I did not read carefully enough.

> The lines of text must be such that, were they not followed by the setext heading underline, they would be interpreted as a paragraph: they cannot be interpretable as a code fence, **ATX heading**, block quote, thematic break,list item, or HTML block.
