### ISSUE TITLE
GitHub-flavored Markdown?

### ISSUE THREAD

**Issue by MisterY** [commonmark/CommonMark#522]
Hi,

I could not see anything related to this topic. Any intention to support some additional features, like checkboxes, like in GH-flavored Markdown?

**Comment by MisterY** [comment]
This was actually meant for https://github.com/atlassian/commonmark-java but, nonetheless, I'm wondering if the spec might include some useful extensions like 

- [ ] checkboxes

**Comment by MisterY** [comment]
OK, found it!
https://github.com/commonmark/CommonMark/wiki/Deployed-Extensions#bullet-list

**Comment by Crissov** [comment]
Please note #520, although task lists are not fully covered yet.
