### ISSUE TITLE
Complicated case with link titles with parenthesis

### ISSUE THREAD

**Issue by mity** [commonmark/CommonMark#526]
A link title, variant in parenthesis, is described as follows in the spec. 0.28:

> a sequence of zero or more characters between matching parentheses (`(...)`), including a `)` character only if it is backslash-escaped.

That makes me wonder whether allowing un-escaped `(` is good idea or whether it would be better to have some symmetry here.

Also cmark currently transforms 
```
[link](url ((title))
```
 into
```
<p><a href="url" title="(title">link</a></p>
```

Note the title contents having `(` not matched with any `)`, escaped or not.

**Comment by jgm** [comment]
Martin Mitáš <notifications@github.com> writes:

I suppose the "matching parentheses" language isn't so clear.
We could say:  "a sequence of zero or more characters between
an unescaped open parenthesis and the first unescaped close
parenthesis to follow."

I don't have a strong view about disallowing `(`.
