### ISSUE TITLE
Interior strong+emph not parsed

### ISSUE THREAD

**Issue by brson** [commonmark/CommonMark#528]
This doesn't parse like I expect:

```
a***b***c
```

Because of rules 9 & 10 [here](https://spec.commonmark.org/0.28/#can-open-emphasis) it parses as just a single text run with no emphasis.

For my purposes I need that to parse as strong+emphasis, and it seems like a simple addition to the rules makes it work, namely that if both the opener and closer delimiters have a length that are a multiple of 3, then they are considered valid delimiter runs.

Here's a patch to comrak that implements such a rule while still passing the spec suite:

https://github.com/brson/comrak/commit/ac3218b3af117fc5a061277015a1d10ca0575044

cc @kivikakk

**Comment by jgm** [comment]
This change in cmark does the trick:
```c
diff --git a/src/inlines.c b/src/inlines.c
index bab607a..6e92aff 100644
--- a/src/inlines.c
+++ b/src/inlines.c
@@ -642,7 +642,8 @@ static void process_emphasis(subject *subj, delimiter *stack_bottom) {
           // interior closer of size 2 can't match opener of size 1
           // or of size 1 can't match 2
           if (!(closer->can_open || opener->can_close) ||
-              ((opener->length + closer->length) % 3) != 0) {
+             closer->length % 3 == 0 ||
+              (opener->length + closer->length) % 3 != 0) {
             opener_found = true;
             break;
           }
```
This test should be equivalent, because if closer length is a multiple of 3 and the sum of closer and opener length is a multiple of 3, opener length has to be a multiple of 3.  So we don't to test that separately.

I think I'm convinced we should change the spec.
