### ISSUE TITLE
No strikethrough support.

### ISSUE THREAD

**Issue by shubhsherl** [commonmark/CommonMark#529]
\~\~Groot\~\~ should be converted to `<del>Groot</del>`.

**Comment by Crissov** [comment]
Relevant threads:

- [220](https://talk.commonmark.org/t/feature-request-strikethrough-text/220)
- [820](https://talk.commonmark.org/t/strikeout-threw-out-strikethrough-strikes-out-throughout/820)
- [825](https://talk.commonmark.org/t/highlights-strikeout-underlines-spoilers/825)
