### ISSUE TITLE
List item blocks separated by more than one blank line?

### ISSUE THREAD

**Issue by nojb** [commonmark/CommonMark#543]
The description of list items say 
> If a sequence of lines Ls constitute a sequence of blocks Bs starting with a non-whitespace character and not separated from each other by more than one blank line, [...] is a list item with Bs as its contents.

But example 225 says:
> A list item may contain blocks that are separated by more than one blank line.

So, which one is it ? Can the blocks of a list item be separated by more than one blank line ? Am I missing something ?

**Comment by jjoelson** [comment]
I just encountered this same discrepancy. As far as I can tell, the 6 rules defining list items seem to disallow multiple blank lines between blocks, so I think I agree with you that this is a bug in the spec.

**Comment by jgm** [comment]
Nicolás Ojeda Bär <notifications@github.com> writes:

> The description of list items say 
>> If a sequence of lines Ls constitute a sequence of blocks Bs starting with a non-whitespace character and not separated from each other by more than one blank line, [...] is a list item with Bs as its contents.

This is a leftover from an earlier version of the spec, in which two blank lines would end a list. It should be changed.
