### ISSUE TITLE
Feature Request: Image Size Issues

### ISSUE THREAD

**Issue by maxswjeon** [commonmark/CommonMark#547]
Since Github is using commonmarker on Markdown files, (.markdown, .md, .etc...) I came here to suggest new features.
There is no way to resize images if they are bigger than wrapper width. There were some ways to resize them by pipe or additional curly braces (https://gist.github.com/uupaa/f77d2bcf4dc7a294d109)
Is there any further plans for image resizing?

**Comment by maxswjeon** [comment]
# Explanation
There are many ways to implement this, since html's default behavior with width and height of image.

## Idea 1. Using Pipe Character after URL
### Example 1.
```![example1](https://gyazo.com/eb5c5741b6a9a16c692170a41a49c858.png | width=100)``` can be turned to this HTML code : 
```html
<img src="https://gyazo.com/eb5c5741b6a9a16c692170a41a49c858.png" alt="example1" width="100px">
```
### Example 2.
```![example2](https://gyazo.com/eb5c5741b6a9a16c692170a41a49c858.png | width=100 height=200)``` can be turned to this HTML code : 
```html
<img src="https://gyazo.com/eb5c5741b6a9a16c692170a41a49c858.png" alt="example2" width="100px" height="200">
```
### Example 3.
```![example3](https://gyazo.com/eb5c5741b6a9a16c692170a41a49c858.png | class="img-responsive")``` can be turned to this HTML code : 
```html
<img src="https://gyazo.com/eb5c5741b6a9a16c692170a41a49c858.png" alt="example3" class="img-responsive">
```

## Idea 2. Using Pipe Character after Description (Alt text)
### Example 1.
```![example1|100](https://gyazo.com/eb5c5741b6a9a16c692170a41a49c858.png)``` can be turned to this HTML code : 
```html
<img src="https://gyazo.com/eb5c5741b6a9a16c692170a41a49c858.png" alt="example1" width="100px">
```
### Example 2.
```![example2|100x200](https://gyazo.com/eb5c5741b6a9a16c692170a41a49c858.png)``` can be turned to this HTML code : 
```html
<img src="https://gyazo.com/eb5c5741b6a9a16c692170a41a49c858.png" alt="example2" width="100px" height="200">
```
### Example 3.
```![example3|image-responsive](https://gyazo.com/eb5c5741b6a9a16c692170a41a49c858.png)``` can be turned to this HTML code : 
```html
<img src="https://gyazo.com/eb5c5741b6a9a16c692170a41a49c858.png" alt="example3" class="img-responsive">
```

## Idea 3. Using Equal Sign (=)
### Example 1.
```![example1](https://gyazo.com/eb5c5741b6a9a16c692170a41a49c858.png =100)``` can be turned to this HTML code : 
```html
<img src="https://gyazo.com/eb5c5741b6a9a16c692170a41a49c858.png" alt="example1" width="100px">
```
### Example 2.
```![example2](https://gyazo.com/eb5c5741b6a9a16c692170a41a49c858.png =100x200)``` can be turned to this HTML code : 
```html
<img src="https://gyazo.com/eb5c5741b6a9a16c692170a41a49c858.png" alt="example2" width="100px" height="200">
```
### Example 3.
```![example3](https://gyazo.com/eb5c5741b6a9a16c692170a41a49c858.png ="img-responsive")``` can be turned to this HTML code : 
```html
<img src="https://gyazo.com/eb5c5741b6a9a16c692170a41a49c858.png" alt="example3" class="img-responsive">
```

## Idea 4. Using Curly Braces for Style Attributes
### Example 1.
```![example1](https://gyazo.com/eb5c5741b6a9a16c692170a41a49c858.png){: width=100px }``` can be turned to this HTML code : 
```html
<img src="https://gyazo.com/eb5c5741b6a9a16c692170a41a49c858.png" alt="example1" width="100px">
```
### Example 2.
```![example2](https://gyazo.com/eb5c5741b6a9a16c692170a41a49c858.png){: width=100 height=200 }``` can be turned to this HTML code : 
```html
<img src="https://gyazo.com/eb5c5741b6a9a16c692170a41a49c858.png" alt="example2" width="100px" height="200">
```
### Example 3.
```![example3](https://gyazo.com/eb5c5741b6a9a16c692170a41a49c858.png){: class="img-responsive"}``` can be turned to this HTML code : 
```html
<img src="https://gyazo.com/eb5c5741b6a9a16c692170a41a49c858.png" alt="example3" class="img-responsive">
```

**Comment by cokia** [comment]
I think we need this new feature!
I'm pulling for U!

**Comment by Crissov** [comment]
See the thread [Support for Image Dimensions](https://talk.commonmark.org/t/support-for-image-dimensions/148) on the Commonmark Discourse.

By the way, please replace `https://gyazo.com/eb5c5741b6a9a16c692170a41a49c858` by `example` or `foo` to keep the focus on the main issue.

**Comment by maxswjeon** [comment]
Thank you for replying my request. I read the conversation that you have given to me. I agree that markdown is not identical with MS Word. Thank you for pointing the reason.

**Comment by Crissov** [comment]
For what it's worth, these are in a very early state: 

- https://github.com/Crissov/CommonMark/blob/extensions/extensions/image-size.txt
- https://github.com/Crissov/CommonMark/blob/extensions/extensions/attribute.txt
