### ISSUE TITLE
Additional implementations?

### ISSUE THREAD

**Issue by hacktember** [commonmark/CommonMark#553]
Hi! If I wrote an implementation of the CommonMark spec in another programming language would that be helpful for this project or would that be superfluous?

**Comment by colinodell** [comment]
You'd certainly be welcome to add your implementation to the wiki! https://github.com/commonmark/CommonMark/wiki/List-of-CommonMark-Implementations

**Comment by jgm** [comment]
Josh Austin <notifications@github.com> writes:

> As in, if I wrote that implementation and attempted a pull request of that implementation into this project as an additional example implementation alongside the other two that are already here?

We don't plan to host other implementations here, but
as noted there's a wiki where we keep track of
implementations written in various languages...

**Comment by hacktember** [comment]
OK. Thanks!
