### ISSUE TITLE
Description List

### ISSUE THREAD

**Issue by cup** [commonmark/CommonMark#559]
if you put this markdown:

~~~
one two
: three four five six
~~~

it gives you the expected output with kramdown:

~~~html
<dl>
  <dt>one two</dt>
  <dd>three four five six</dd>
</dl>
~~~

but not with commonmark:

~~~html
<p>one two
: three four five six</p>
~~~

this is because kramdown supports Description Lists:

https://kramdown.gettalong.org/syntax#definition-lists

while commonmark only supports it as HTML block:

https://spec.commonmark.org/0.28#html-blocks

references:

- https://developer.mozilla.org/Web/HTML/Element/dl
- https://meta.stackexchange.com/questions/72395

**Comment by cup** [comment]
https://github.com/wallyqs/org-ruby/issues/63

**Comment by jgm** [comment]
Yes, we will consider extensions later, after stabilizing the core.
The place to discuss extensions is talk.commonmark.org.

**Comment by jgm** [comment]
See also #554
