### ISSUE TITLE
Deadline for release of 1.0 has passed

### ISSUE THREAD

**Issue by ygale** [commonmark/CommonMark#561]
The front page of commonmark.org states:

> With your help, we plan to announce a finalized 1.0 spec and test suite in 2018.

I recommend you at least update the web site, as per #447. But really - hasn't enough time passed? Why not declare 1.0 released and let future updates be future versions?

**Comment by jgm** [comment]
1.0 implies stability.  We're not there yet: there are still some changes that need to be made.
I'm sorry about the slow progress.  As for the front page of the website, @coding-horror would have to change that.
