### ISSUE TITLE
Add test for [text](<url\>)

### ISSUE THREAD

**Issue by andersk** [commonmark/CommonMark#562]
From commonmark/commonmark.js#158: there’s a discrepancy between cmark and commonmark.js on `[text](<url\>)`. cmark gives

```html
<p>[text](&lt;url&gt;)</p>
```

while commonmark.js previously gave

```html
<p><a href="url%5C">text</a></p>
```

and was just fixed in Git to give

```html
<p><a href="%3Curl%3E">text</a></p>
```

which seems most consistent with the spec.

**Comment by jgm** [comment]
Brought cmark into conformance.
