### ISSUE TITLE
Feature Request: Source maps

### ISSUE THREAD

**Issue by SLaks** [commonmark/CommonMark#57]
It would be great to click in the preview pane in a Markdown editor & select the piece of source Markdown that rendered to that text. 

Can you add an option to generate source maps so that editors can support this?

This is also necessary for synchronized scrolling.

/cc @am11 @madskristensen

**Comment by colinodell** [comment]
+1

**Comment by jgm** [comment]
A lot of useful discussion here, but this doesn't belong in the repository for the spec.
