### ISSUE TITLE
spec.txt not valid CommonMark?

### ISSUE THREAD

**Issue by stain** [commonmark/CommonMark#606]
[spec.txt](https://github.com/commonmark/commonmark-spec/blob/master/spec.txt) starts with:

```markdown
---
title: CommonMark Spec
author: John MacFarlane
version: 0.29
date: '2019-04-06'
license: '[CC-BY-SA 4.0](http://creativecommons.org/licenses/by-sa/4.0/)'
...

# Introduction

## What is Markdown?
```

I cannot find a definition of this `--- ...` block in <https://spec.commonmark.org/0.29/>  and wonder why it is not rendered (or why spec.txt is not valid CommonMark).

**Comment by jgm** [comment]
YAML blocks aren't part of the spec.  It's an unsupported extension.
`lcmark` looks for such a block at the beginning, interprets it, and treats the remainder of the file as commonmark.

**Comment by Crissov** [comment]
Sure, but it doesnʼt harm if the core specification anticipates such extensions. It does not necessarily need to explain in detail why at least four hyphens are recommended.
