### ISSUE TITLE
How tabs are expanded to spaces? I'm confused.

### ISSUE THREAD

**Issue by appsubscribe** [commonmark/CommonMark#74]
The spec states that "Tabs in lines are expanded to spaces, with a tab stop of 4 characters". But when I look at the html result. The first tab only got 1 space?

```
foo→baz→→bim    |  <p>foo baz     bim</p>
```

**Comment by hayd** [comment]
The wording in the spec is still confusing (at least to me). Though I get it now, if it helps someone else:

    "1\t22\t333\t4444\t5" becomes "1   22  333 4444    5"

It would be great to elaborate this aspect of the spec (not sure if there is a better wording though).
