### ISSUE TITLE
Split this up into atomic repositories, move them to the CommonMark organization.

### ISSUE THREAD

**Issue by Bengt** [commonmark/CommonMark#99]
Currently this repository is home of the CommonMark spec, the CommonMark website and both the CommonMark JavaScript and C implementations. This forces users to pull in a lot of code respectively text when they only need one of the both. To enable users to work on the spec or the the C implementation or the JavaScript implementation, this repository should be split up into four new repositories:
- CommonMark-Spec  
  The CommonMark specification. (and tools to preprocess/test against it)
- CommonMark-C  
  A CommonMark implementation in C. (and the build / test system)
- CommonMark-JavaScript  
  A CommonMark implementation in JavaScript. (and the build / test system)
- commonmark.github.io  
  The CommonMark organization's website.

To help users with navigating these repositories, they should reside in the CommonMark organization. This would also enable language-specific CI systems to be used with each of the language-specific repositories.

**Comment by puzrin** [comment]
+1 for org. 2 years passed :)

**Comment by jgm** [comment]
This has happened.
